;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2021 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-6CCC-38BF-48                      |
; |                             IDA PRO 7.6 SP1                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 5613637D267CF8D0BF3FF1E396D7929526CD5221CB8AF06349528C8BEDCED1A0
; Input MD5    : FD04C4616BB559E646937EFFDD343A09
; Input CRC32  : 90FA1539
; Processor       : 68020
; Target assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"
; ===========================================================================
; Segment type: Pure code
; segment "ROM"
; ROM segment
Sys_VectorTable:    dc.l    $FFFFFF00                   ; DATA XREF: ROM:Boss_SniperHoneyviperAssetSet   o  ; was: dword_0
                                        ; ROM:Boss_FlyingNeoAssetSet   o
                dc.l    Reset
                dc.l    BusErr
                dc.l    AdrErr
                dc.l    InvOpCode
                dc.l    DivBy0
                dc.l    Check
                dc.l    TrapV
                dc.l    GPF
                dc.l    Trace
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    IRQ7
                dc.l    IRQ7
                dc.l    IRQ7
                dc.l    $FFFFEE00
                dc.l    IRQ7
                dc.l    VBLANK
                dc.l    IRQ7
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Trap15
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
                dc.l    Reserv3F
CopyRights:     dc.b    'SEGA MEGA DRIVE (C)SEGA 1995.FEBALIEN SOLDIER                  '
                dc.b    '                 ALIEN SOLDIER                                 '
                dc.b    '  GM G-004130-00'
Checksum:       dc.w    $834F                           ; DATA XREF: Reset+164   o
Peripherials:   dc.b    'J               '
RomStart:       dc.l    0
RomEnd:         dc.l    RomFinalPaddingByte
RamStart:       dc.l    M68K_RAM_PHYSICAL
RamEnd:         dc.l    M68K_RAM_END_PHYSICAL
SramCode:       dc.b    '            '
ModemCode:      dc.b    '            '
Reserved:       dc.b    '                                        '
CountryCode:    dc.b    'B               '

; External research associates several dormant records and patch experiments
; with prerelease content. The ROM itself proves entity types, resource lists,
; and call paths, but does not prove every community-supplied character name or
; that every reachable-looking record is unused. Keep those claims out of the
; source API; docs/unused_content.md records them with explicit evidence limits
