;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2021 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-6CCC-38BF-48                      |
; |                             IDA PRO 7.6 SP1                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 5613637D267CF8D0BF3FF1E396D7929526CD5221CB8AF06349528C8BEDCED1A0
; Input MD5    : FD04C4616BB559E646937EFFDD343A09
; Input CRC32  : 90FA1539
; Processor       : 68020
; Target assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"
; ===========================================================================
; Segment type: Pure code
; segment "ROM"
; ROM segment
dword_0:        dc.l $FFFFFF00          ; DATA XREF: ROM:stru_113AA   o
                                        ; ROM:stru_11408   o ...
                dc.l Reset
                dc.l BusErr
                dc.l AdrErr
                dc.l InvOpCode
                dc.l DivBy0
                dc.l Check
                dc.l TrapV
                dc.l GPF
                dc.l Trace
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l IRQ7
                dc.l IRQ7
                dc.l IRQ7
                dc.l $FFFFEE00
                dc.l IRQ7
                dc.l VBLANK
                dc.l IRQ7
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Trap15
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
                dc.l Reserv3F
CopyRights:     dc.b 'SEGA MEGA DRIVE (C)SEGA 1995.FEBALIEN SOLDIER                  '
                dc.b '                 ALIEN SOLDIER                                 '
                dc.b '  GM G-004130-00'
Checksum:       dc.w $834F              ; DATA XREF: Reset+164   o
Peripherials:   dc.b 'J               '
RomStart:       dc.l         0
RomEnd:         dc.l byte_1FFFFF
RamStart:       dc.l M68K_RAM_PHYSICAL
RamEnd:         dc.l M68K_RAM_END_PHYSICAL
SramCode:       dc.b '            '
ModemCode:      dc.b '            '
Reserved:       dc.b '                                        '
CountryCode:    dc.b 'B               '

; ===============================================================================
; UNUSED/SCRAPPED CONTENT DOCUMENTATION
; Sources: The Cutting Room Floor - https://tcrf.net/Alien_Soldier
;          YouTube Research (Zetaman, Oct-Nov 2021)
; ===============================================================================
; This disassembly contains several complete but unused game elements that were
; cut during development. All structures remain fully intact in the ROM.
;
; UNUSED BOSSES (6 total):
;   - $01C0 "Love Penguin"  : Hand-shaped boss (line ~21034)
;   - $03EC "Lambda Bunny"  : Cowboy rabbit boss (stru_115A8, line ~21092)
;   - $03FC "Dragon"        : Dragon boss (line ~21138)
;   - $3F0  Unknown Boss    : Identity unknown (stru_115C4, line ~21098)
;   - $3F4  Unknown Boss    : Possibly Mantis or Sigma Fox (stru_115E0, line ~21120)
;   - Additional bosses in unused Jampan Area (Praying Mantis, Sigma Fox)
;
; UNUSED GRAPHICS (2 structures):
;   - Intro Cutscene Sprites: Kaede + unknown man (stru_12910, line ~23283)
;   - Unknown Graphics      : 314 bytes, purpose unknown (stru_128F2, line ~23266)
;
; UNUSED STAGES/AREAS:
;   - Jampan Area: 3-4 unused boss stages (activate via ROM patches)
;   - Laboratory Stage: Plays cutscene then crashes
;   - Epsilon 1 Cutscene: Pre-battle cutscene from magazine preview
;
; UNUSED FEATURES:
;   - Dialogue System: Pre-boss battle dialogue exchanges (ROM 0x00B462)
;   - Story Text Screens: Narrative text between stages (ROM 0x01E276)
;   - Seven Force Variants: Harpy Force & Nemesis Force (non-functional)
;
; DEBUG/TEST CODE:
;   - Boss_JampanDebugController: Developer test function (line ~88482)
;     Allows manual parameter control via controller input
;
; LOADER FUNCTIONS:
;   -Stage_InitBossPhase2 (line ~16561): Lambda Bunny palette loader
;   -Stage_InitBossPhase3 (line ~16598): Unknown boss $3F0 palette loader
;   -Stage_InitBossPhase4 (line ~16646): Unknown boss $3F4 palette loader
;   -Stage_InitCutsceneData (line ~22688): Intro sprite loader
;
; ACTIVATION CODES:
;   See docs/unused_content_activation.md for ROM patch codes
;   Global enable: ROM 0x00036C = 4E71 4E71 (NOP NOP)
;
; All unused content is marked with "UNUSED:" comments at relevant locations.
; No code logic has been modified - documentation only.
; ===============================================================================

