struc_1 macro p0,p1
    dc.w p0
    dc.l p1
struc_1 endm

struc_2 macro p0,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14
    dc.w p0
    dc.l p1
    dc.w p2
    dc.b p3
    dc.b p4
    dc.w p5
    dc.w p6
    dc.w p7
    dc.w p8
    dc.w p9
    dc.w p10
    dc.w p11
    dc.b p12
    dc.b p13
    dc.l p14
struc_2 endm

struc_3 macro p0,p1,p2
    dc.w p0
    dc.w p1
    dc.l p2
struc_3 endm

struc_5 macro p0,p1,p2,p3,p4
    dc.w p0
    dc.w p1
    dc.l p2
    dc.l p3
    dc.w p4
struc_5 endm

struc_6 macro p0,p1,p2
    dc.w p0
    dc.l p1
    dc.w p2
struc_6 endm

struc_7 macro p0,p1,p2
    dc.w p0
    dc.l p1
    dc.l p2
struc_7 endm

