import csv

procedures = [
    # 7 Forces win cutscene (33 procedures)
    ('sub_EDE0', '7 forces win cutscene', '51120', 'Cutscene_SevenForcesCamera1', 'Camera scroll handler 1', 'Cutscene', 'analyzed'),
    ('sub_5531A', '7 forces win cutscene', '51120', 'Cutscene_SevenForcesExplosions', 'Spawns explosion effects', 'Cutscene', 'analyzed'),
    ('sub_55716', '7 forces win cutscene', '51120', 'Cutscene_SevenForcesTransition', 'Transition after victory', 'Cutscene', 'analyzed'),
    ('sub_EAA4', '7 forces win cutscene', '51300', 'Cutscene_SevenForcesState1', 'Cutscene state handler 1', 'Cutscene', 'analyzed'),
    ('sub_EABA', '7 forces win cutscene', '51300', 'Cutscene_SevenForcesState2', 'Cutscene state handler 2', 'Cutscene', 'analyzed'),
    ('sub_EE0A', '7 forces win cutscene', '51300', 'Cutscene_SevenForcesCamera2', 'Camera scroll handler 2', 'Cutscene', 'analyzed'),
    ('sub_553CC', '7 forces win cutscene', '51300', 'Cutscene_SevenForcesWaitState', 'Wait state with timer', 'Cutscene', 'analyzed'),
    ('sub_EADA', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesState3', 'Cutscene state handler 3', 'Cutscene', 'analyzed'),
    ('sub_EAF2', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesState4', 'Cutscene state handler 4', 'Cutscene', 'analyzed'),
    ('sub_EB1A', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesState5', 'Cutscene state handler 5', 'Cutscene', 'analyzed'),
    ('sub_EB48', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesState6', 'Cutscene state handler 6', 'Cutscene', 'analyzed'),
    ('sub_EE36', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesCamera3', 'Camera scroll handler 3', 'Cutscene', 'analyzed'),
    ('sub_EF7A', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesLoadGraphics', 'Loads cutscene graphics', 'Graphics', 'analyzed'),
    ('sub_EFE2', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesCheckComplete', 'Checks cutscene completion', 'Cutscene', 'analyzed'),
    ('sub_19EF6', '7 forces win cutscene', '51840', 'Cutscene_SevenForcesSoundEffect', 'Plays victory sound effect', 'Cutscene', 'analyzed'),
    ('sub_553EE', '7 forces win cutscene', '52020', 'Cutscene_SevenForcesEffect1', 'Visual effect handler 1', 'Cutscene', 'analyzed'),
    ('sub_5540C', '7 forces win cutscene', '52020', 'Cutscene_SevenForcesEffect2', 'Visual effect handler 2', 'Cutscene', 'analyzed'),
    ('sub_5543A', '7 forces win cutscene', '52020', 'Cutscene_SevenForcesEffect3', 'Visual effect handler 3', 'Cutscene', 'analyzed'),
    ('sub_5554C', '7 forces win cutscene', '52020', 'Cutscene_SevenForcesEffect4', 'Visual effect handler 4', 'Cutscene', 'analyzed'),
    ('sub_F0F0', '7 forces win cutscene', '52560', 'Stage_TransitionInit', 'Stage transition initialization', 'Stage', 'analyzed'),
    ('sub_F19A', '7 forces win cutscene', '52560', 'Stage_TransitionGraphics', 'Transition graphics handler', 'Stage', 'analyzed'),
    ('sub_FB3A', '7 forces win cutscene', '52560', 'Stage_ScrollUpdate1', 'Scroll update handler 1', 'Stage', 'analyzed'),
    ('sub_FB72', '7 forces win cutscene', '52560', 'Stage_ScrollUpdate2', 'Scroll update handler 2', 'Stage', 'analyzed'),
    ('sub_FBA8', '7 forces win cutscene', '52560', 'Stage_ScrollUpdate3', 'Scroll update handler 3', 'Stage', 'analyzed'),
    ('sub_12128', '7 forces win cutscene', '52560', 'Stage_LoadTiles1', 'Loads stage tiles 1', 'Graphics', 'analyzed'),
    ('sub_125EE', '7 forces win cutscene', '52560', 'Stage_LoadTiles2', 'Loads stage tiles 2', 'Graphics', 'analyzed'),
    ('sub_12648', '7 forces win cutscene', '52560', 'Stage_LoadPalette', 'Loads stage palette', 'Graphics', 'analyzed'),
    ('sub_330A6', '7 forces win cutscene', '52560', 'Enemy_TrackerWinMain', 'Tracker enemy main (win cutscene)', 'Enemy', 'analyzed'),
    ('sub_332D0', '7 forces win cutscene', '52560', 'Enemy_TrackerWinMovement', 'Tracker movement (win cutscene)', 'Enemy', 'analyzed'),
    ('sub_334B2', '7 forces win cutscene', '52560', 'Enemy_TrackerWinFollow', 'Tracker follow player (win cutscene)', 'Enemy', 'analyzed'),
    ('sub_334DC', '7 forces win cutscene', '52560', 'Enemy_TrackerWinInitSprite', 'Initialize tracker sprite (win)', 'Enemy', 'analyzed'),
    ('sub_334FE', '7 forces win cutscene', '52560', 'Enemy_TrackerWinSpawnBullet', 'Spawns tracker bullets (win)', 'Enemy', 'analyzed'),
    ('sub_1A06A', '7 forces win cutscene', '53280', 'Gfx_UpdateTrackerSprites', 'Updates tracker sprites', 'Graphics', 'analyzed'),
    # Asteroids (Stage 21) - Tracker enemy system (12 procedures)
    ('sub_330F2', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21State1', 'Tracker state 1 (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_33124', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21State2', 'Tracker state 2 (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_3313A', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21SpawnInit', 'Tracker spawn init (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_3322E', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Attack1', 'Tracker attack 1 (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_33258', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Attack2', 'Tracker attack 2 (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_33358', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Damage', 'Tracker damage (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_33402', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Destroy', 'Tracker destroy (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_334D4', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21OffScreen', 'Tracker off-screen (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_335CA', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Collision', 'Tracker collision (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_335EE', 'Asteroids (Stage 21)', '53640', 'Projectile_TrackerSt21Bullet', 'Tracker bullet (Stage 21)', 'Projectile', 'analyzed'),
    ('sub_33602', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21UpdateAI', 'Tracker AI update (Stage 21)', 'Enemy', 'analyzed'),
    ('sub_33640', 'Asteroids (Stage 21)', '53640', 'Enemy_TrackerSt21Animation', 'Tracker animation (Stage 21)', 'Enemy', 'analyzed'),
    # Asteroids stage graphics (3 procedures)
    ('sub_F218', 'Asteroids (Stage 21)', '53640', 'Stage_AsteroidsTransition', 'Transition to asteroids', 'Stage', 'analyzed'),
    ('sub_F242', 'Asteroids (Stage 21)', '55080', 'Stage_AsteroidsScrollHandler', 'Asteroids scroll handler', 'Stage', 'analyzed'),
    ('sub_FB24', 'Asteroids (Stage 21)', '55080', 'Stage_AsteroidsGraphicsUpdate', 'Graphics update handler', 'Stage', 'analyzed'),
    # Destroyer Prototype boss (32 procedures)
    ('sub_F26C', 'Destroyer Prototype boss', '55260', 'Boss_DestroyerProtoTransition', 'Transition to boss', 'Boss', 'analyzed'),
    ('sub_F288', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoInit', 'Boss initialization', 'Boss', 'analyzed'),
    ('sub_314D8', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoMain', 'Main boss handler', 'Boss', 'analyzed'),
    ('sub_31540', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoGfxUpdate', 'Boss graphics update', 'Boss', 'analyzed'),
    ('sub_31594', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoIntroInit', 'Intro animation init', 'Boss', 'analyzed'),
    ('sub_316C4', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoIntroMove', 'Intro movement', 'Boss', 'analyzed'),
    ('sub_316F8', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoCollision', 'Boss collision handler', 'Boss', 'analyzed'),
    ('sub_3171C', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoBounds', 'Boss boundary check', 'Boss', 'analyzed'),
    ('sub_31736', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoVelocity', 'Boss velocity handler', 'Boss', 'analyzed'),
    ('sub_31768', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoState1', 'Boss state handler 1', 'Boss', 'analyzed'),
    ('sub_31774', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoState2', 'Boss state handler 2', 'Boss', 'analyzed'),
    ('sub_317FE', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoState3', 'Boss state handler 3', 'Boss', 'analyzed'),
    ('sub_31F86', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoState4', 'Boss state handler 4', 'Boss', 'analyzed'),
    ('sub_31FB4', 'Destroyer Prototype boss', '55440', 'Boss_DestroyerProtoState5', 'Boss state handler 5', 'Boss', 'analyzed'),
    ('sub_31830', 'Destroyer Prototype boss', '55620', 'Boss_DestroyerProtoAttack1', 'Attack pattern 1', 'Boss', 'analyzed'),
    ('sub_318AC', 'Destroyer Prototype boss', '55620', 'Boss_DestroyerProtoAttack2', 'Attack pattern 2', 'Boss', 'analyzed'),
    ('sub_3178A', 'Destroyer Prototype boss', '55800', 'Boss_DestroyerProtoTurretClose', 'Close turret hatches', 'Boss', 'analyzed'),
    ('sub_317A8', 'Destroyer Prototype boss', '55800', 'Boss_DestroyerProtoTurretOpen', 'Open turret hatches', 'Boss', 'analyzed'),
    ('sub_318EC', 'Destroyer Prototype boss', '55800', 'Boss_DestroyerProtoAttack3', 'Attack pattern 3', 'Boss', 'analyzed'),
    ('sub_31A28', 'Destroyer Prototype boss', '55800', 'Boss_DestroyerProtoAttack4', 'Attack pattern 4', 'Boss', 'analyzed'),
    ('sub_1A0C8', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoDefeatInit', 'Defeat sequence init', 'Boss', 'analyzed'),
    ('sub_1A122', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoDefeatAnim', 'Defeat animation handler', 'Boss', 'analyzed'),
    ('sub_31A46', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoShootPattern1', 'Shooting pattern 1', 'Boss', 'analyzed'),
    ('sub_31A7E', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoShootPattern2', 'Shooting pattern 2', 'Boss', 'analyzed'),
    ('sub_31AA2', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoShootPattern3', 'Shooting pattern 3', 'Boss', 'analyzed'),
    ('sub_31D9A', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoSpawnProjectile1', 'Spawns projectile type 1', 'Boss', 'analyzed'),
    ('sub_31DF6', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoSpawnProjectile2', 'Spawns projectile type 2', 'Boss', 'analyzed'),
    ('sub_31E9C', 'Destroyer Prototype boss', '55980', 'Boss_DestroyerProtoSpawnProjectile3', 'Spawns projectile type 3', 'Boss', 'analyzed'),
    ('sub_32208', 'Destroyer Prototype boss', '56160', 'Projectile_DestroyerProtoMain', 'Projectile main handler', 'Projectile', 'analyzed'),
    ('sub_1ADC', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoUpdateSprites', 'Updates boss sprites', 'Boss', 'analyzed'),
    ('sub_F31C', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoAnimationScript', 'Animation script interpreter', 'Boss', 'analyzed'),
    ('sub_FCF4', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoPaletteInit', 'Palette initialization', 'Boss', 'analyzed'),
]

with open('batch_analysis.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['old_name', 'scene', 'frame', 'new_name', 'description', 'category', 'status'])
    writer.writerows(procedures)

print(f'Created batch_analysis.csv with {len(procedures)} procedures')
