import csv

procedures = [
    # Destroyer Prototype boss completion (5 procedures)
    ('sub_FD32', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoRenderSegments', 'Renders boss segments', 'Boss', 'analyzed'),
    ('sub_29F08', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoVRAMSetup', 'VRAM setup handler', 'Boss', 'analyzed'),
    ('sub_31F5E', 'Destroyer Prototype boss', '56160', 'Boss_DestroyerProtoPaletteFade', 'Palette fade effect', 'Boss', 'analyzed'),
    ('sub_3231A', 'Destroyer Prototype boss', '56160', 'Projectile_DestroyerProtoUpdate', 'Projectile update handler', 'Projectile', 'analyzed'),
    ('sub_F350', 'Destroyer Prototype boss', '56340', 'Boss_DestroyerProtoGraphicsCleanup', 'Graphics cleanup handler', 'Boss', 'analyzed'),
    # Stage 22 - Flying enemies and objects (42 procedures)
    ('sub_2E9FC', 'Stage 22', '56880', 'Enemy_FlyerMain', 'Flying enemy main handler', 'Enemy', 'analyzed'),
    ('sub_2EA0E', 'Stage 22', '56880', 'Enemy_FlyerDispatcher', 'Flying enemy dispatcher', 'Enemy', 'analyzed'),
    ('sub_2EA28', 'Stage 22', '56880', 'Enemy_FlyerSpawnInit', 'Flying enemy spawn init', 'Enemy', 'analyzed'),
    ('sub_2EA58', 'Stage 22', '56880', 'Enemy_FlyerMovement1', 'Flying enemy movement 1', 'Enemy', 'analyzed'),
    ('sub_2EABE', 'Stage 22', '56880', 'Enemy_FlyerMovement2', 'Flying enemy movement 2', 'Enemy', 'analyzed'),
    ('sub_2EB00', 'Stage 22', '56880', 'Enemy_FlyerAttack', 'Flying enemy attack', 'Enemy', 'analyzed'),
    ('sub_2EB94', 'Stage 22', '56880', 'Enemy_FlyerSpawnProjectile', 'Spawns flyer projectile', 'Enemy', 'analyzed'),
    ('sub_2EBD2', 'Stage 22', '56880', 'Enemy_FlyerCheckBounds1', 'Boundary check 1', 'Enemy', 'analyzed'),
    ('sub_2EBE0', 'Stage 22', '56880', 'Enemy_FlyerCheckBounds2', 'Boundary check 2', 'Enemy', 'analyzed'),
    ('sub_2EBF4', 'Stage 22', '56880', 'Enemy_FlyerAccelerate', 'Acceleration handler', 'Enemy', 'analyzed'),
    ('sub_2EC14', 'Stage 22', '56880', 'Enemy_FlyerTrackPlayer', 'Track player movement', 'Enemy', 'analyzed'),
    ('sub_2EED6', 'Stage 22', '56880', 'Enemy_FlyerAdjustVelocity', 'Velocity adjustment', 'Enemy', 'analyzed'),
    ('sub_2EF1A', 'Stage 22', '56880', 'Enemy_FlyerExplode', 'Explosion handler', 'Enemy', 'analyzed'),
    ('sub_33664', 'Stage 22', '56880', 'Enemy_FlyerCollision', 'Collision detection', 'Enemy', 'analyzed'),
    ('sub_3367A', 'Stage 22', '56880', 'Enemy_FlyerDamage', 'Damage handler', 'Enemy', 'analyzed'),
    ('sub_1213E', 'Stage 22', '56880', 'Stage22_LoadGraphics', 'Loads stage graphics', 'Graphics', 'analyzed'),
    ('sub_2EA9A', 'Stage 22', '57060', 'Enemy_FlyerState1', 'Flyer state handler 1', 'Enemy', 'analyzed'),
    ('sub_2EC34', 'Stage 22', '57060', 'Enemy_FlyerState2', 'Flyer state handler 2', 'Enemy', 'analyzed'),
    ('sub_2EC84', 'Stage 22', '57060', 'Enemy_FlyerState3', 'Flyer state handler 3', 'Enemy', 'analyzed'),
    ('sub_2EC9E', 'Stage 22', '57060', 'Enemy_FlyerState4', 'Flyer state handler 4', 'Enemy', 'analyzed'),
    ('sub_2ED22', 'Stage 22', '57060', 'Enemy_FlyerState5', 'Flyer state handler 5', 'Enemy', 'analyzed'),
    ('sub_2ED62', 'Stage 22', '57060', 'Enemy_FlyerState6', 'Flyer state handler 6', 'Enemy', 'analyzed'),
    ('sub_2ED9C', 'Stage 22', '57060', 'Enemy_FlyerState7', 'Flyer state handler 7', 'Enemy', 'analyzed'),
    ('sub_2EDD8', 'Stage 22', '57060', 'Enemy_FlyerState8', 'Flyer state handler 8', 'Enemy', 'analyzed'),
    ('sub_336A8', 'Stage 22', '57240', 'Enemy_FlyerUpdateSprites1', 'Updates flyer sprites 1', 'Enemy', 'analyzed'),
    ('sub_336B4', 'Stage 22', '57240', 'Enemy_FlyerUpdateSprites2', 'Updates flyer sprites 2', 'Enemy', 'analyzed'),
    ('sub_336EA', 'Stage 22', '57240', 'Enemy_FlyerAnimation1', 'Flyer animation 1', 'Enemy', 'analyzed'),
    ('sub_33976', 'Stage 22', '57240', 'Enemy_FlyerAnimation2', 'Flyer animation 2', 'Enemy', 'analyzed'),
    ('sub_339DE', 'Stage 22', '57240', 'Enemy_FlyerAnimation3', 'Flyer animation 3', 'Enemy', 'analyzed'),
    ('sub_33A66', 'Stage 22', '57240', 'Enemy_FlyerAnimation4', 'Flyer animation 4', 'Enemy', 'analyzed'),
    ('sub_33BA4', 'Stage 22', '57240', 'Enemy_FlyerAnimation5', 'Flyer animation 5', 'Enemy', 'analyzed'),
    ('sub_33BD0', 'Stage 22', '57240', 'Enemy_FlyerAnimation6', 'Flyer animation 6', 'Enemy', 'analyzed'),
    ('sub_2EE0C', 'Stage 22', '57420', 'Projectile_FlyerBullet1', 'Flyer bullet projectile 1', 'Projectile', 'analyzed'),
    ('sub_2EE44', 'Stage 22', '57420', 'Projectile_FlyerBullet2', 'Flyer bullet projectile 2', 'Projectile', 'analyzed'),
    ('sub_2EE80', 'Stage 22', '57420', 'Projectile_FlyerBullet3', 'Flyer bullet projectile 3', 'Projectile', 'analyzed'),
    ('sub_33AE0', 'Stage 22', '57420', 'Projectile_FlyerUpdate1', 'Projectile update 1', 'Projectile', 'analyzed'),
    ('sub_33B14', 'Stage 22', '57420', 'Projectile_FlyerUpdate2', 'Projectile update 2', 'Projectile', 'analyzed'),
    ('sub_33BEC', 'Stage 22', '57420', 'Projectile_FlyerUpdate3', 'Projectile update 3', 'Projectile', 'analyzed'),
    ('sub_33C22', 'Stage 22', '57420', 'Projectile_FlyerUpdate4', 'Projectile update 4', 'Projectile', 'analyzed'),
    ('sub_2EEC0', 'Stage 22', '57780', 'Enemy_FlyerDestroy', 'Destroy flyer enemy', 'Enemy', 'analyzed'),
    ('sub_2EECC', 'Stage 22', '57780', 'Enemy_FlyerDecelerate', 'Deceleration handler', 'Enemy', 'analyzed'),
    ('sub_337D6', 'Stage 22', '57780', 'Enemy_FlyerRenderUpdate', 'Render update handler', 'Enemy', 'analyzed'),
    ('sub_FC8C', 'Stage 22', '57960', 'Stage22_GraphicsUpdate1', 'Graphics update 1', 'Graphics', 'analyzed'),
    ('sub_1B7DC', 'Stage 22', '57960', 'Stage22_GraphicsUpdate2', 'Graphics update 2', 'Graphics', 'analyzed'),
    # Shield Viper boss (31 procedures)
    ('sub_F3E0', 'Shield Viper boss', '58680', 'Boss_ShieldViperTransition', 'Transition to boss', 'Boss', 'analyzed'),
    ('sub_F402', 'Shield Viper boss', '58680', 'Boss_ShieldViperInit', 'Boss initialization', 'Boss', 'analyzed'),
    ('sub_F42C', 'Shield Viper boss', '58680', 'Boss_ShieldViperGraphicsInit', 'Graphics initialization', 'Boss', 'analyzed'),
    ('sub_F448', 'Shield Viper boss', '58680', 'Boss_ShieldViperPaletteSetup', 'Palette setup', 'Boss', 'analyzed'),
    ('sub_FC74', 'Shield Viper boss', '58680', 'Boss_ShieldViperScrollSetup', 'Scroll setup handler', 'Boss', 'analyzed'),
    ('sub_4258', 'Shield Viper boss', '58860', 'Boss_ShieldViperLoadTiles', 'Loads boss tiles', 'Graphics', 'analyzed'),
    ('sub_FE68', 'Shield Viper boss', '58860', 'Boss_ShieldViperRenderBackground', 'Renders background', 'Graphics', 'analyzed'),
    ('sub_4DDD2', 'Shield Viper boss', '58860', 'Boss_ShieldViperMain', 'Main boss handler', 'Boss', 'analyzed'),
    ('sub_4E060', 'Shield Viper boss', '58860', 'Boss_ShieldViperDispatcher', 'Boss state dispatcher', 'Boss', 'analyzed'),
    ('sub_4E198', 'Shield Viper boss', '58860', 'Boss_ShieldViperIntroInit', 'Intro animation init', 'Boss', 'analyzed'),
    ('sub_4E2A0', 'Shield Viper boss', '58860', 'Boss_ShieldViperIntroMove', 'Intro movement', 'Boss', 'analyzed'),
    ('sub_4E2CE', 'Shield Viper boss', '58860', 'Boss_ShieldViperIntroStop', 'Intro stop position', 'Boss', 'analyzed'),
    ('sub_4E2F0', 'Shield Viper boss', '58860', 'Boss_ShieldViperBattleStart', 'Battle start initialization', 'Boss', 'analyzed'),
    ('sub_4F26E', 'Shield Viper boss', '58860', 'Boss_ShieldViperIdleState', 'Idle state handler', 'Boss', 'analyzed'),
    ('sub_4F37C', 'Shield Viper boss', '58860', 'Boss_ShieldViperAttackState1', 'Attack state 1 handler', 'Boss', 'analyzed'),
    ('sub_4F4CC', 'Shield Viper boss', '58860', 'Boss_ShieldViperAttackState2', 'Attack state 2 handler', 'Boss', 'analyzed'),
    ('sub_4F4F8', 'Shield Viper boss', '58860', 'Boss_ShieldViperSegmentUpdate', 'Updates snake segments', 'Boss', 'analyzed'),
    ('sub_4F530', 'Shield Viper boss', '58860', 'Boss_ShieldViperMovement1', 'Movement pattern 1', 'Boss', 'analyzed'),
    ('sub_4F70C', 'Shield Viper boss', '58860', 'Boss_ShieldViperMovement2', 'Movement pattern 2', 'Boss', 'analyzed'),
    ('sub_4F794', 'Shield Viper boss', '58860', 'Boss_ShieldViperMovement3', 'Movement pattern 3', 'Boss', 'analyzed'),
    ('sub_4F83C', 'Shield Viper boss', '59040', 'Boss_ShieldViperShootPattern1', 'Shooting pattern 1', 'Boss', 'analyzed'),
    ('sub_4F84E', 'Shield Viper boss', '59040', 'Boss_ShieldViperShootPattern2', 'Shooting pattern 2', 'Boss', 'analyzed'),
    ('sub_4F886', 'Shield Viper boss', '59040', 'Boss_ShieldViperShootPattern3', 'Shooting pattern 3', 'Boss', 'analyzed'),
    ('sub_4E64A', 'Shield Viper boss', '59040', 'Boss_ShieldViperSpawnProjectile1', 'Spawns projectile type 1', 'Boss', 'analyzed'),
    ('sub_4ED96', 'Shield Viper boss', '59040', 'Boss_ShieldViperSpawnProjectile2', 'Spawns projectile type 2', 'Boss', 'analyzed'),
    ('sub_4F090', 'Shield Viper boss', '59040', 'Boss_ShieldViperCollision', 'Boss collision handler', 'Boss', 'analyzed'),
    ('sub_4F38A', 'Shield Viper boss', '59040', 'Boss_ShieldViperDamage', 'Boss damage handler', 'Boss', 'analyzed'),
    ('sub_4F74A', 'Shield Viper boss', '59040', 'Boss_ShieldViperUpdateSprites', 'Updates boss sprites', 'Boss', 'analyzed'),
    ('sub_4F75E', 'Shield Viper boss', '59040', 'Boss_ShieldViperAnimationScript', 'Animation script interpreter', 'Boss', 'analyzed'),
    ('sub_4F77A', 'Shield Viper boss', '59040', 'Projectile_ShieldViperMain', 'Projectile main handler', 'Projectile', 'analyzed'),
    ('sub_4F78A', 'Shield Viper boss', '59040', 'Projectile_ShieldViperBullet', 'Projectile bullet handler', 'Projectile', 'analyzed'),
]

with open('batch_analysis.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['old_name', 'scene', 'frame', 'new_name', 'description', 'category', 'status'])
    writer.writerows(procedures)

print(f'Created batch_analysis.csv with {len(procedures)} procedures')
